"""Тестовые фикстуры реестров для demo3.py. ТЕСТОВЫЕ ДАННЫЕ, не реальная компания."""

INN = "7701234567"

EGRUL = {
    "full_name": 'Общество с ограниченной ответственностью "МОСТАР"',
    "short_name": 'ООО "МОСТАР"',
    "location": "г. Москва",
    "address": "115035, г. Москва, ул. Садовническая, д. 1",
    "email": "MOSTAR.7@YANDEX.RU",
    "ogrn": "1157746000000",
    "registration_date": "12.05.2015",
    "formation_method": "Создание юридического лица",
    "registering_authority_name": "Межрайонная ИФНС России № 46 по г. Москве",
    "inn": INN,
    "kpp": "770101001",
    "tax_registration_date": "12.05.2015",
    "tax_authority_name": "ИФНС России № 1 по г. Москве",
    "sfr_registration_number": None,
    "sfr_registration_date": None,
    "sfr_authority_name": None,
    "director": {
        "surname": "Строк",
        "name": "Марина",
        "patronymic": "Ивановна",
        "full_name": None,
        "inn": None,
        "ogrn": None,
        "position": "Генеральный директор",
        "gender": "Женский",
        "citizenship": "Российская Федерация",
        "share_value_rub": None,
        "share_percent": None,
    },
    "director_disqualification_start": None,
    "director_disqualification_end": None,
    "director_disqualification_court_date": None,
    "capital_type": "Уставный капитал",
    "capital_amount_rub": 10000,
    "founders": [],
    "okved_main": {"code": "74.10", "name": "Деятельность специализированная в области дизайна"},
    "okved_additional": [
        {"code": "62.09", "name": "Деятельность, связанная с использованием вычислительной "
                                    "техники и информационных технологий, прочая"},
    ],
    "notes": [],
}

MSP = {
    "name": 'ООО "МОСТАР"',
    "subject_type": "UL",
    "category": 1,
    "ogrn": EGRUL["ogrn"],
    "inn": INN,
    "main_activity_code": "74.10",
    "main_activity_name": "Деятельность специализированная в области дизайна",
    "region_code": "77",
    "is_new": False,
    "date_registered": "10.08.2016",
    "date_excluded": None,
    "phone": None,
    "email": "MOSTAR.7@YANDEX.RU",
    "website": None,
    "has_licenses": False,
    "is_hitech": False,
    "is_partnership": False,
    "is_social": False,
}
